/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/ethanfu0124-bit/vault-powershell (private)
Do not edit this file directly.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultPowerShellPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/vault-path.ts
var import_obsidian = require("obsidian");
function getVaultRootPath(vault) {
  if (vault === null || vault === void 0) {
    return null;
  }
  const adapter = vault.adapter;
  if (!(adapter instanceof import_obsidian.FileSystemAdapter)) {
    return null;
  }
  return adapter.getBasePath();
}

// src/powershell/candidates.ts
var import_node_path = require("node:path");
var PATH_CANDIDATE = "pwsh.exe";
var PROGRAM_FILES_RELATIVE = ["PowerShell", "7", "pwsh.exe"];
var DOTNET_TOOLS_RELATIVE = [".dotnet", "tools", "pwsh.exe"];
function buildCandidates(env = process.env) {
  const raw = [{ path: PATH_CANDIDATE, source: "PATH" }];
  const programFiles = env.ProgramFiles;
  if (programFiles !== void 0 && programFiles !== "") {
    raw.push({ path: (0, import_node_path.join)(programFiles, ...PROGRAM_FILES_RELATIVE), source: "ProgramFiles" });
  }
  const userProfile = env.USERPROFILE;
  if (userProfile !== void 0 && userProfile !== "") {
    raw.push({
      path: (0, import_node_path.join)(userProfile, ...DOTNET_TOOLS_RELATIVE),
      source: "UserProfileDotnetTools"
    });
  }
  return dedupeCandidates(raw);
}
function dedupeCandidates(candidates) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const candidate of candidates) {
    const key = candidate.path.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    out.push(candidate);
  }
  return out;
}

// src/powershell/version-probe.ts
var import_node_child_process = require("node:child_process");

// src/powershell/types.ts
var PROBE_ARGS = [
  "-NoLogo",
  "-NoProfile",
  "-NonInteractive",
  "-Command",
  "$PSVersionTable.PSVersion.Major"
];
var PROBE_TIMEOUT_MS = 5e3;

// src/powershell/version-probe.ts
function runExecFile(file, args, options) {
  return new Promise((resolve, reject) => {
    (0, import_node_child_process.execFile)(file, args, options, (error, stdout, _stderr) => {
      if (error !== null) {
        reject(error);
        return;
      }
      const text = typeof stdout === "string" ? stdout : stdout.toString("utf8");
      resolve({ stdout: text });
    });
  });
}
async function probeMajorVersion(exePath, options = {}) {
  var _a;
  try {
    const { stdout } = await runExecFile(exePath, [...PROBE_ARGS], {
      shell: false,
      windowsHide: true,
      timeout: (_a = options.timeoutMs) != null ? _a : PROBE_TIMEOUT_MS,
      encoding: "utf8",
      env: process.env
    });
    return parseMajorVersion(stdout);
  } catch (e) {
    return null;
  }
}
function parseMajorVersion(rawOutput) {
  const trimmed = rawOutput.trim();
  if (!/^[0-9]+$/.test(trimmed)) {
    return null;
  }
  const major = Number.parseInt(trimmed, 10);
  if (!Number.isSafeInteger(major)) {
    return null;
  }
  return major >= 7 ? major : null;
}

// src/powershell/launcher.ts
var import_node_child_process2 = require("node:child_process");
function launchInteractive(verified, vaultPath) {
  return new Promise((resolve) => {
    let settled = false;
    let child;
    try {
      child = (0, import_node_child_process2.spawn)(verified.path, ["-WorkingDirectory", vaultPath], {
        cwd: vaultPath,
        env: process.env,
        shell: false,
        windowsHide: false,
        detached: false,
        stdio: "inherit"
      });
    } catch (error) {
      resolve({ ok: false, code: "UNKNOWN", error });
      return;
    }
    child.once("error", (error) => {
      if (settled) {
        return;
      }
      settled = true;
      const code = error.code;
      resolve({
        ok: false,
        code: code === "ENOENT" ? "ENOENT" : "UNKNOWN",
        error
      });
    });
    child.once("spawn", () => {
      var _a;
      if (settled) {
        return;
      }
      settled = true;
      resolve({ ok: true, pid: (_a = child.pid) != null ? _a : 0 });
    });
    child.unref();
  });
}

// src/powershell/finder.ts
var PowerShellFinder = class {
  constructor(deps) {
    this.deps = deps;
    this.verified = null;
    this.resolving = null;
  }
  /** The currently cached result, if any. */
  get cached() {
    return this.verified;
  }
  /** Resolve once; concurrent callers share the same in-flight probe chain. */
  resolve() {
    if (this.verified !== null) {
      return Promise.resolve(this.verified);
    }
    if (this.resolving !== null) {
      return this.resolving;
    }
    this.resolving = this.findBest().finally(() => {
      this.resolving = null;
    });
    return this.resolving;
  }
  /** Drop the cached result (e.g. the cached executable is gone). */
  invalidate() {
    this.verified = null;
  }
  async findBest() {
    var _a, _b, _c, _d;
    const candidates = this.deps.buildCandidates(this.deps.env);
    for (const candidate of candidates) {
      const major = await this.deps.probeMajorVersion(candidate.path);
      if (major !== null) {
        this.verified = { path: candidate.path, majorVersion: major };
        (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `verified pwsh: ${candidate.path} (major ${major})`);
        return this.verified;
      }
      (_d = (_c = this.deps).debug) == null ? void 0 : _d.call(_c, `rejected candidate ${candidate.source}: ${candidate.path}`);
    }
    return null;
  }
};

// src/main.ts
var RIBBON_ICON = "terminal";
var RIBBON_TOOLTIP = "Open PowerShell at vault root";
var NOTICE_NOT_WINDOWS = "Vault PowerShell only supports Obsidian Desktop on Windows.";
var NOTICE_NO_VAULT_PATH = "Unable to resolve the local vault path.";
var NOTICE_NOT_FOUND = "PowerShell 7 or later was not found. Install PowerShell and restart Obsidian.";
var NOTICE_START_FAILED = "PowerShell could not be started. Check the developer console for details.";
var VaultPowerShellPlugin = class extends import_obsidian2.Plugin {
  constructor(app, manifest, deps) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    super(app, manifest);
    this.platform = (_a = deps == null ? void 0 : deps.platform) != null ? _a : process.platform;
    this.finder = new PowerShellFinder({
      buildCandidates: (_c = (_b = deps == null ? void 0 : deps.finder) == null ? void 0 : _b.buildCandidates) != null ? _c : buildCandidates,
      probeMajorVersion: (_e = (_d = deps == null ? void 0 : deps.finder) == null ? void 0 : _d.probeMajorVersion) != null ? _e : probeMajorVersion,
      env: (_f = deps == null ? void 0 : deps.finder) == null ? void 0 : _f.env,
      debug: (_h = (_g = deps == null ? void 0 : deps.finder) == null ? void 0 : _g.debug) != null ? _h : ((message) => console.debug(`[Vault PowerShell] ${message}`))
    });
  }
  onload() {
    this.addRibbonIcon(RIBBON_ICON, RIBBON_TOOLTIP, () => {
      void this.openPowerShell();
    });
  }
  /**
   * Click handler: platform check -> vault path -> find/verify pwsh ->
   * launch. On `ENOENT` at launch time the cache is cleared and a single
   * retry is performed (never more than once per click, never recursive).
   */
  async openPowerShell() {
    if (this.platform !== "win32") {
      new import_obsidian2.Notice(NOTICE_NOT_WINDOWS);
      return;
    }
    const vaultPath = getVaultRootPath(this.app.vault);
    if (vaultPath === null) {
      new import_obsidian2.Notice(NOTICE_NO_VAULT_PATH);
      return;
    }
    const verified = await this.finder.resolve();
    if (verified === null) {
      new import_obsidian2.Notice(NOTICE_NOT_FOUND);
      return;
    }
    const outcome = await launchInteractive(verified, vaultPath);
    if (outcome.ok) {
      return;
    }
    if (outcome.code === "ENOENT") {
      this.finder.invalidate();
      const reVerified = await this.finder.resolve();
      if (reVerified === null) {
        new import_obsidian2.Notice(NOTICE_NOT_FOUND);
        return;
      }
      const retry = await launchInteractive(reVerified, vaultPath);
      if (retry.ok) {
        return;
      }
      console.error(
        "[Vault PowerShell] launch failed on retry",
        retry.code,
        retry.error
      );
      new import_obsidian2.Notice(NOTICE_START_FAILED);
      return;
    }
    console.error("[Vault PowerShell] launch failed", outcome.code, outcome.error);
    new import_obsidian2.Notice(NOTICE_START_FAILED);
  }
};
