/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/ethanffu/vault-powershell
Do not edit this file directly.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultPowerShellPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/vault-path.ts
var import_obsidian = require("obsidian");
function getLocalAdapter(vault) {
  if (vault === null || vault === void 0) {
    return null;
  }
  const adapter = vault.adapter;
  return adapter instanceof import_obsidian.FileSystemAdapter ? adapter : null;
}
function getVaultRootPath(vault) {
  const adapter = getLocalAdapter(vault);
  if (adapter === null) {
    return null;
  }
  return adapter.getBasePath();
}
function getFolderPath(vault, folder) {
  if (folder === null || folder === void 0) {
    return null;
  }
  const adapter = getLocalAdapter(vault);
  if (adapter === null) {
    return null;
  }
  const normalized = folder.path.replace(/^\/+|\/+$/g, "");
  if (normalized === "") {
    return adapter.getBasePath();
  }
  return adapter.getFullPath(normalized);
}

// src/powershell/candidates.ts
var import_node_path = require("node:path");
var PATH_CANDIDATE = "pwsh.exe";
var PROGRAM_FILES_RELATIVE = ["PowerShell", "7", "pwsh.exe"];
var DOTNET_TOOLS_RELATIVE = [".dotnet", "tools", "pwsh.exe"];
function buildCandidates(env = process.env) {
  const raw = [{ path: PATH_CANDIDATE, source: "PATH" }];
  const programFiles = env.ProgramFiles;
  if (programFiles !== void 0 && programFiles !== "") {
    raw.push({ path: (0, import_node_path.join)(programFiles, ...PROGRAM_FILES_RELATIVE), source: "ProgramFiles" });
  }
  const userProfile = env.USERPROFILE;
  if (userProfile !== void 0 && userProfile !== "") {
    raw.push({
      path: (0, import_node_path.join)(userProfile, ...DOTNET_TOOLS_RELATIVE),
      source: "UserProfileDotnetTools"
    });
  }
  return dedupeCandidates(raw);
}
function dedupeCandidates(candidates) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const candidate of candidates) {
    const key = candidate.path.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    out.push(candidate);
  }
  return out;
}

// src/powershell/version-probe.ts
var import_node_child_process = require("node:child_process");

// src/powershell/types.ts
var PROBE_ARGS = [
  "-NoLogo",
  "-NoProfile",
  "-NonInteractive",
  "-Command",
  "$PSVersionTable.PSVersion.Major"
];
var PROBE_TIMEOUT_MS = 5e3;

// src/powershell/version-probe.ts
function runExecFile(file, args, options) {
  return new Promise((resolve, reject) => {
    (0, import_node_child_process.execFile)(file, args, options, (error, stdout, _stderr) => {
      if (error !== null) {
        reject(error);
        return;
      }
      const text = typeof stdout === "string" ? stdout : stdout.toString("utf8");
      resolve({ stdout: text });
    });
  });
}
async function probeMajorVersion(exePath, options = {}) {
  var _a;
  try {
    const { stdout } = await runExecFile(exePath, [...PROBE_ARGS], {
      shell: false,
      windowsHide: true,
      timeout: (_a = options.timeoutMs) != null ? _a : PROBE_TIMEOUT_MS,
      encoding: "utf8",
      env: process.env
    });
    return parseMajorVersion(stdout);
  } catch (e) {
    return null;
  }
}
function parseMajorVersion(rawOutput) {
  const trimmed = rawOutput.trim();
  if (!/^[0-9]+$/.test(trimmed)) {
    return null;
  }
  const major = Number.parseInt(trimmed, 10);
  if (!Number.isSafeInteger(major)) {
    return null;
  }
  return major >= 7 ? major : null;
}

// src/powershell/launcher.ts
var import_node_child_process2 = require("node:child_process");
var WINDOWS_TERMINAL = "wt.exe";
function spawnDirect(verified, targetDir) {
  return spawnPwsh(
    verified.path,
    ["-WorkingDirectory", targetDir],
    targetDir,
    "inherit"
  );
}
function spawnHosted(verified, targetDir) {
  return spawnPwsh(
    WINDOWS_TERMINAL,
    ["-w", "0", verified.path, "-WorkingDirectory", targetDir],
    targetDir,
    "ignore"
  );
}
function spawnPwsh(executable, args, targetDir, stdio) {
  return new Promise((resolve) => {
    let settled = false;
    let child;
    try {
      child = (0, import_node_child_process2.spawn)(executable, args, {
        cwd: targetDir,
        env: process.env,
        shell: false,
        windowsHide: false,
        detached: false,
        stdio
      });
    } catch (error) {
      resolve({ ok: false, code: "UNKNOWN", error });
      return;
    }
    child.once("error", (error) => {
      if (settled) {
        return;
      }
      settled = true;
      const code = error.code;
      resolve({
        ok: false,
        code: code === "ENOENT" ? "ENOENT" : "UNKNOWN",
        error
      });
    });
    child.once("spawn", () => {
      var _a;
      if (settled) {
        return;
      }
      settled = true;
      resolve({ ok: true, pid: (_a = child.pid) != null ? _a : 0 });
    });
    child.unref();
  });
}
function launchInteractive(verified, targetDir) {
  if (targetDir.includes(";")) {
    return Promise.resolve({
      ok: false,
      code: "UNKNOWN",
      error: new Error(
        "Refusing to launch PowerShell for a path containing a semicolon (;)."
      )
    });
  }
  return spawnHosted(verified, targetDir).then((outcome) => {
    if (outcome.ok) {
      return outcome;
    }
    if (outcome.code === "ENOENT") {
      return spawnDirect(verified, targetDir);
    }
    return outcome;
  });
}

// src/powershell/finder.ts
var PowerShellFinder = class {
  constructor(deps) {
    this.deps = deps;
    this.verified = null;
    this.resolving = null;
  }
  /** The currently cached result, if any. */
  get cached() {
    return this.verified;
  }
  /** Resolve once; concurrent callers share the same in-flight probe chain. */
  resolve() {
    if (this.verified !== null) {
      return Promise.resolve(this.verified);
    }
    if (this.resolving !== null) {
      return this.resolving;
    }
    this.resolving = this.findBest().finally(() => {
      this.resolving = null;
    });
    return this.resolving;
  }
  /** Drop the cached result (e.g. the cached executable is gone). */
  invalidate() {
    this.verified = null;
  }
  async findBest() {
    var _a, _b, _c, _d;
    const candidates = this.deps.buildCandidates(this.deps.env);
    for (const candidate of candidates) {
      const major = await this.deps.probeMajorVersion(candidate.path);
      if (major !== null) {
        this.verified = { path: candidate.path, majorVersion: major };
        (_b = (_a = this.deps).debug) == null ? void 0 : _b.call(_a, `verified pwsh: ${candidate.path} (major ${major})`);
        return this.verified;
      }
      (_d = (_c = this.deps).debug) == null ? void 0 : _d.call(_c, `rejected candidate ${candidate.source}: ${candidate.path}`);
    }
    return null;
  }
};

// src/main.ts
var RIBBON_ICON = "terminal";
var RIBBON_TOOLTIP = "Open PowerShell at vault root";
var HIDE_RIBBON_BODY_CLASS = "hide-vault-powershell-ribbon";
var MENU_ITEM_TITLE = "Open PowerShell here";
var MENU_ITEM_ICON = "terminal";
var NOTICE_NOT_WINDOWS = "Open PowerShell here only supports Obsidian Desktop on Windows.";
var NOTICE_NO_VAULT_PATH = "Unable to resolve the local vault path.";
var NOTICE_NOT_FOUND = "PowerShell 7 or later was not found. Install PowerShell and restart Obsidian.";
var NOTICE_START_FAILED = "PowerShell could not be started. Check the developer console for details.";
var NOTICE_SEMICOLON = "PowerShell cannot be opened for paths containing a semicolon (;).";
var VaultPowerShellPlugin = class extends import_obsidian2.Plugin {
  constructor(app, manifest, deps) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    super(app, manifest);
    this.ribbonEl = null;
    this.ribbonObserver = null;
    /**
     * Single-folder context-menu handler (Obsidian's public `file-menu`
     * event). Shows the item only for exactly one `TFolder` on Windows with a
     * local file system adapter. The target path is resolved when the item is
     * clicked, not when the menu is built.
     */
    this.onFileMenu = (menu, file) => {
      if (this.platform !== "win32") {
        return;
      }
      if (!(file instanceof import_obsidian2.TFolder)) {
        return;
      }
      if (!(this.app.vault.adapter instanceof import_obsidian2.FileSystemAdapter)) {
        return;
      }
      const folder = file;
      menu.addItem((item) => {
        item.setTitle(MENU_ITEM_TITLE).setIcon(MENU_ITEM_ICON).onClick(() => {
          void this.openPowerShell(getFolderPath(this.app.vault, folder));
        });
      });
    };
    this.platform = (_a = deps == null ? void 0 : deps.platform) != null ? _a : process.platform;
    this.finder = new PowerShellFinder({
      buildCandidates: (_c = (_b = deps == null ? void 0 : deps.finder) == null ? void 0 : _b.buildCandidates) != null ? _c : buildCandidates,
      probeMajorVersion: (_e = (_d = deps == null ? void 0 : deps.finder) == null ? void 0 : _d.probeMajorVersion) != null ? _e : probeMajorVersion,
      env: (_f = deps == null ? void 0 : deps.finder) == null ? void 0 : _f.env,
      debug: (_h = (_g = deps == null ? void 0 : deps.finder) == null ? void 0 : _g.debug) != null ? _h : ((message) => console.debug(`[Open PowerShell here] ${message}`))
    });
  }
  onload() {
    const ribbonEl = this.addRibbonIcon(RIBBON_ICON, RIBBON_TOOLTIP, () => {
      void this.openPowerShell(getVaultRootPath(this.app.vault));
    });
    ribbonEl.addClass("vault-powershell-ribbon");
    this.ribbonEl = ribbonEl;
    this.setupRibbonVisibilityEnforcement();
    this.registerEvent(this.app.workspace.on("file-menu", this.onFileMenu));
  }
  onunload() {
    var _a;
    (_a = this.ribbonObserver) == null ? void 0 : _a.disconnect();
    this.ribbonObserver = null;
    this.ribbonEl = null;
    super.onunload();
  }
  /**
   * Enforce the Style Settings hide toggle in JS, on top of the styles.css
   * rule: when `HIDE_RIBBON_BODY_CLASS` is present on <body>, hide the
   * ribbon element via inline style. This makes the toggle work regardless
   * of theme CSS or future ribbon DOM changes (the CSS rule alone failed in
   * the user's environment until the body-class mismatch was fixed).
   *
   * Skipped outside a DOM environment (automated tests).
   */
  setupRibbonVisibilityEnforcement() {
    if (typeof document === "undefined" || typeof MutationObserver === "undefined") {
      return;
    }
    const apply = () => {
      if (this.ribbonEl === null) {
        return;
      }
      this.ribbonEl.style.display = document.body.classList.contains(
        HIDE_RIBBON_BODY_CLASS
      ) ? "none" : "";
    };
    this.ribbonObserver = new MutationObserver(apply);
    this.ribbonObserver.observe(document.body, {
      attributes: true,
      attributeFilter: ["class"]
    });
    apply();
  }
  /**
   * Shared launch flow for both entry points (ribbon and folder context
   * menu): platform check -> semicolon guard -> target path -> find/verify
   * pwsh -> launch. On `ENOENT` at launch time the cache is cleared and a
   * single retry is performed (never more than once per click, never
   * recursive).
   *
   * `targetDir` is the directory PowerShell should open: the vault root for
   * the ribbon, the right-clicked folder's absolute path for the menu.
   */
  async openPowerShell(targetDir) {
    if (this.platform !== "win32") {
      new import_obsidian2.Notice(NOTICE_NOT_WINDOWS);
      return;
    }
    if (targetDir === null) {
      new import_obsidian2.Notice(NOTICE_NO_VAULT_PATH);
      return;
    }
    if (targetDir.includes(";")) {
      new import_obsidian2.Notice(NOTICE_SEMICOLON);
      return;
    }
    const verified = await this.finder.resolve();
    if (verified === null) {
      new import_obsidian2.Notice(NOTICE_NOT_FOUND);
      return;
    }
    const outcome = await launchInteractive(verified, targetDir);
    if (outcome.ok) {
      return;
    }
    if (outcome.code === "ENOENT") {
      this.finder.invalidate();
      const reVerified = await this.finder.resolve();
      if (reVerified === null) {
        new import_obsidian2.Notice(NOTICE_NOT_FOUND);
        return;
      }
      const retry = await launchInteractive(reVerified, targetDir);
      if (retry.ok) {
        return;
      }
      console.error(
        "[Open PowerShell here] launch failed on retry",
        retry.code,
        retry.error
      );
      new import_obsidian2.Notice(NOTICE_START_FAILED);
      return;
    }
    console.error("[Open PowerShell here] launch failed", outcome.code, outcome.error);
    new import_obsidian2.Notice(NOTICE_START_FAILED);
  }
};
